import "../public/css/one-panel.css";
import Footer from "./components/footer";

export const metadata = {
  title: "Nicequest",
  description: "Generated by create next app",
  charset: "utf-8",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className="bg-neutral-100">
        {children}
        <Footer />
      </body>
    </html>
  );
}
